[flights]
uri = "../components/lib/flights.wasm"
expects = ["http-client"]
exposed = true

[hotels]
uri = "../components/lib/hotels.wasm"
expects = ["http-client"]
exposed = true

[http-client]
uri = "../components/lib/http-client.wasm"
expects = ["wasip2", "http"]
enables = "exposed"

[http]
uri = "wasmtime:http"
enables = "unexposed"

[wasip2]
uri = "wasmtime:wasip2"
enables = "unexposed"
