[workspace]
members = [
    "counter",
    "flights",
    "greeter",
    "hotels",
    "incrementor",
    "intercepting-greeter",
    "publisher",
    "rest-client",
]
resolver = "3"

[workspace.dependencies]
wit-bindgen = "0.44"
