[hello]
uri = "../components/lib/greeter.wasm"
exposed = true

[aloha]
uri = "../components/lib/greeter.wasm"
config.greeting = "Aloha"
enables = "exposed"
exposed = true

[pirate]
uri = "../components/lib/intercepting-greeter.wasm"
config.prefix = "Ahoy and "
config.suffix = " Arrr!"
intercepts = ["aloha"]
exposed = true
